// ─── Surgery Risk Types ───────────────────────────────────────────────────────

export const OPCOES_CIRURGIA = [
  // Baixo Risco (<1%)
  { valor: "breast", rotulo: "Mama", risco: "baixo", vascular: false },
  { valor: "dental", rotulo: "Procedimentos dentários", risco: "baixo", vascular: false },
  { valor: "thyroid", rotulo: "Tireoide", risco: "baixo", vascular: false },
  { valor: "eye", rotulo: "Ocular", risco: "baixo", vascular: false },
  { valor: "gynecologic_minor", rotulo: "Ginecológica minor", risco: "baixo", vascular: false },
  { valor: "orthopedic_minor", rotulo: "Ortopédica minor (menisco)", risco: "baixo", vascular: false },
  { valor: "reconstructive", rotulo: "Reconstrutiva", risco: "baixo", vascular: false },
  { valor: "superficial", rotulo: "Superfície", risco: "baixo", vascular: false },
  { valor: "urologic_minor", rotulo: "Urológica minor (RTU)", risco: "baixo", vascular: false },
  { valor: "vats_minor", rotulo: "VATS minor", risco: "baixo", vascular: false },
  // Risco Intermediário (1–5%)
  { valor: "carotid_asymptomatic", rotulo: "Carótida assintomática", risco: "intermediario", vascular: true },
  { valor: "carotid_endarterectomy", rotulo: "Endarterectomia carótida (sintomática)", risco: "intermediario", vascular: true },
  { valor: "peripheral_angioplasty", rotulo: "Angioplastia arterial periférica", risco: "intermediario", vascular: true },
  { valor: "endovascular_aortic", rotulo: "Aneurisma de aorta endovascular", risco: "intermediario", vascular: true },
  { valor: "head_neck", rotulo: "Cabeça e pescoço", risco: "intermediario", vascular: false },
  { valor: "intraperitoneal", rotulo: "Intraperitoneal (colecistectomia, hérnia hiatal, esplenectomia)", risco: "intermediario", vascular: false },
  { valor: "intrathoracic", rotulo: "Intratorácica non-major", risco: "intermediario", vascular: false },
  { valor: "neurologic", rotulo: "Neurológica", risco: "intermediario", vascular: false },
  { valor: "orthopedic_major", rotulo: "Ortopédica major", risco: "intermediario", vascular: false },
  { valor: "renal_transplant", rotulo: "Transplante renal", risco: "intermediario", vascular: false },
  { valor: "urologic_major", rotulo: "Urológica major", risco: "intermediario", vascular: false },
  { valor: "gynecologic_major", rotulo: "Ginecológica major", risco: "intermediario", vascular: false },
  // Alto Risco (>5%)
  { valor: "aortic_vascular_major", rotulo: "Aorta e vascular major", risco: "alto", vascular: true },
  { valor: "peripheral_open", rotulo: "Revascularização periférica aberta (isquemia aguda) / amputação", risco: "alto", vascular: true },
  { valor: "carotid_angioplasty", rotulo: "Angioplastia carótida (sintomática)", risco: "alto", vascular: true },
  { valor: "adrenal_resection", rotulo: "Ressecção adrenal", risco: "alto", vascular: false },
  { valor: "pancreatic", rotulo: "Pancreática", risco: "alto", vascular: false },
  { valor: "liver_biliary", rotulo: "Fígado e vias biliares", risco: "alto", vascular: false },
  { valor: "esophagectomy", rotulo: "Esofagectomia", risco: "alto", vascular: false },
  { valor: "pneumectomy", rotulo: "Pneumectomia (VATS ou aberta)", risco: "alto", vascular: false },
  { valor: "lung_transplant", rotulo: "Transplante pulmonar", risco: "alto", vascular: false },
  { valor: "liver_transplant", rotulo: "Transplante hepático", risco: "alto", vascular: false },
  { valor: "total_cystectomy", rotulo: "Cistectomia total", risco: "intermediario", vascular: false },
  { valor: "bowel_perforation", rotulo: "Reparo de perfuração intestinal", risco: "alto", vascular: false },
];

// ─── Functional Capacity Questionnaire ────────────────────────────────────────

export const PERGUNTAS_FUNCIONAIS = [
  { id: "housework_light", rotulo: "Fazer trabalhos leves em casa, como juntar o lixo ou lavar a louça?", mets: 2.7 },
  { id: "self_care", rotulo: "Cuidar de si mesmo: vestir-se, alimentar-se, tomar banho?", mets: 2.75 },
  { id: "walk_flat", rotulo: "Caminhar uma quadra ou duas, no plano?", mets: 2.75 },
  { id: "housework_moderate", rotulo: "Fazer trabalhos moderados em casa, como passar o aspirador de pó, varrer o chão ou guardar/carregar mantimentos?", mets: 3.5 },
  { id: "climb_stairs", rotulo: "Subir um lance de escadas ou caminhar em uma subida?", mets: 5.5 },
  { id: "yard_work", rotulo: "Fazer trabalhos no jardim/quintal, como usar o rastelo, juntar folhas ou usar a máquina de cortar grama?", mets: 4.5 },
  { id: "sexual_activity", rotulo: "Ter atividade sexual?", mets: 5.25 },
  { id: "recreation_moderate", rotulo: "Participar de atividades recreacionais moderadas, como jogar boliche, dançar, jogar tênis em dupla?", mets: 6 },
  { id: "sports", rotulo: "Participar de atividades esportivas, como natação, ou tênis individual, ou futebol?", mets: 7.5 },
  { id: "housework_heavy", rotulo: "Fazer trabalhos pesados em casa, como esfregar/lavar o piso, ou levantar ou deslocar móveis pesados?", mets: 8 },
  { id: "run_short", rotulo: "Correr uma distância curta?", mets: 8 },
];

// ─── Wizard Steps ─────────────────────────────────────────────────────────────

export const ETAPAS_WIZARD = [
  { id: 1, titulo: "Dados do Paciente", subtitulo: "Informações gerais, comorbidades e medicamentos" },
  { id: 2, titulo: "Cirurgia e Condições Ativas", subtitulo: "Procedimento e condições cardiovasculares" },
  { id: 3, titulo: "Índice de Risco", subtitulo: "RCRI ou VSG conforme tipo cirúrgico" },
  { id: 4, titulo: "Resultado", subtitulo: "Relatório e recomendações" },
];

// ─── Default Form State ───────────────────────────────────────────────────────

export const dadosPacienteInicial = {
  nome: "",
  idade: undefined,
  obesidade: false,
  ic_conhecida: false,
  doenca_valvar_conhecida: false,
  dac_conhecida: false,
  eco_recente: false,
  piora_sintomas: false,
  usa_aas: false,
  prevencao_aas: "",
  usa_clopidogrel: false,
  usa_ticagrelor: false,
  usa_prasugrel: false,
  usa_varfarina: false,
  indicacao_varfarina: "",
  chadsvasc_varfarina: undefined,
  avc_3m_varfarina: false,
  tempo_tev_varfarina: "",
  trombofilia_varfarina: "",
  neoplasia_ativa_varfarina: false,
  atividades_funcionais: [],
  mets: 1,
  tipo_cirurgia: "",
  risco_cirurgia: "",
  eh_vascular: false,
  cv_coronaria_aguda: false,
  cv_aorta_instavel: false,
  cv_edema_pulmonar_agudo: false,
  cv_choque_cardiogenico: false,
  cv_ic_nyha_3_4: false,
  cv_angina_ccs_3_4: false,
  cv_arritmia_grave: false,
  cv_has_nao_controlada: false,
  cv_fa_alta_resposta: false,
  cv_hap_sintomatica: false,
  cv_valvopatia_grave: false,
  rcri_cirurgia_alto_risco: false,
  rcri_doenca_coronaria: false,
  rcri_ic: false,
  rcri_cerebrovascular: false,
  rcri_diabetes_insulina: false,
  rcri_creatinina_acima_2: false,
  vsg_faixa_etaria: "",
  vsg_dac: false,
  vsg_ic: false,
  vsg_dpoc: false,
  vsg_creatinina_acima_1_8: false,
  vsg_tabagismo: false,
  vsg_diabetes_insulina: false,
  vsg_betabloqueador_cronico: false,
  vsg_revasc_previa: false,
};
